# Generated by rust2rpm
%bcond_with check
%global debug_package %{nil}

%global crate odds

Name:           rust-%{crate}
Version:        0.3.1
Release:        2%{?dist}
Summary:        Odds and ends — collection miscellania

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/odds
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(rawpointer/default) >= 0.1.0 with crate(rawpointer/default) < 0.2.0)
BuildRequires:  (crate(rawslice/default) >= 0.1.0 with crate(rawslice/default) < 0.2.0)
BuildRequires:  (crate(unchecked-index/default) >= 0.2.2 with crate(unchecked-index/default) < 0.3.0)
%if %{with check}
BuildRequires:  (crate(itertools/default) >= 0.7.2 with crate(itertools/default) < 0.8.0)
BuildRequires:  (crate(lazy_static/default) >= 0.2.2 with crate(lazy_static/default) < 0.3.0)
BuildRequires:  (crate(memchr/default) >= 2.0.0 with crate(memchr/default) < 3.0.0)
BuildRequires:  (crate(quickcheck) >= 0.4.1 with crate(quickcheck) < 0.5.0)
%endif

%global _description \
Odds and ends — collection miscellania. Extra functionality for slices\
(`.find()`, `RevSlice`), strings and other things. Things in odds may move to\
more appropriate crates if we find them.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.rst
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+docs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+docs-devel %{_description}

This package contains library source intended for building other packages
which use "docs" feature of "%{crate}" crate.

%files       -n %{name}+docs-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+std-string-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-string-devel %{_description}

This package contains library source intended for building other packages
which use "std-string" feature of "%{crate}" crate.

%files       -n %{name}+std-string-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+std-vec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-vec-devel %{_description}

This package contains library source intended for building other packages
which use "std-vec" feature of "%{crate}" crate.

%files       -n %{name}+std-vec-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages
which use "unstable" feature of "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.3.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sun Apr 28 17:05:59 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.1-1
- Initial package
